apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: new-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jrichter/new-quarkus:eb250898d920e5000eb300fc59935d016dd007f2@sha256:c3281c7238034b41b3b75aac0659dad68a1c66c25fad2cc4ecd8fc988b547947
          name: container-image
